# -*- coding: utf-8 -*-
"""simplelinearregresion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3dw1PDk7nGtHIFJVHqxTjcRixcmWpoA
"""

##Linear Regression
#Dataset:seaborn.tips
#Model:Simple Linear regression
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd

data=sb.load_dataset('tips')
(data.head())
#(data.info())
#data.describe()

plt.scatter(data["total_bill"],data["tip"])
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.title("Total Bill vs Tip")

"""Observstion
1.As the bill increases tip increases
2.relationship=straight line so we can linear regression.
3.Feature &Target Separation




"""

#4.Feature &Target Separation
x=data[["total_bill"]]
y=data[["tip"]]
#5.train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
#80% training.20% testing
#5.feature Standardization
#''''1Compare the CoEfficient Fairly
#2.avoid Domaince of large Values
#3.prepare for ridge/lasso

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

# IMP
# -fit only on training dat
# -prevents the dataleakage

#Train Linear Regression Model
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train_sc,y_train)
print(lr.coef_[0] )
print(lr.intercept_)
y_pred=lr.predict(x_test_sc)
print(y_pred)
# 8.Model Evaluation
from sklearn.metrics import r2_score
import numpy as np
from sklearn.metrics import mean_squared_error

r2=r2_score(y_test,y_pred)
print(r2)
mse=mean_squared_error(y_test,y_pred)
print(mse)
rmse=np.sqrt(mse)
print(rmse)
# Visualize the beat fit line
plt.scatter(x,y)
plt.plot(x, lr.predict(sc.transform(x)), color='red')
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.title("Total Bill vs Tip")

#Input output Real time
bill_amt=float(input("Enter the bill amount:"))
tip_amt=lr.predict(sc.transform([[bill_amt]]))
print(tip_amt)